//ASCII stands for American Standard Code for Information Interchange
//The problem that was solved for the most part was regarding the early printers that often lacked graphics ability, and thus, characters were used in place of graphic marks
println("   *******     *******   ");
println("  *********   *********  ");
println(" *********** *********** ");
println("*************************");
println("*************************");
println("*************************");
println("*************************");
println(" *********************** "); 
println("  *********************  "); 
println("   *******************   "); 
println("    *****************    ");
println("     ***************     ");
println("      *************      ");
println("       ***********       ");
println("        *********        ");
println("         *******         ");
println("          *****          ");
println("           ***           ");
println("            *            ");
println("|_____|");
println("|=====|");
println("|--w--|");
println("   .");
println("      .' |");
println("    .'   |");
println("    /`-._'");
println("   /   /");
println("  /   /");
println(" /   /");
println("`-./");
println(" )");
println("'"); 
